// Common domain types and interfaces
export type {
  BaseFilterCriteria,
  BaseSortField,
  CreateUseCase,
  DateRange,
  DeleteUseCase,
  GetAllUseCase,
  GetByIdUseCase,
  GroupResult,
  GroupUseCase,
  LayoutConfig,
  PaginatedResult,
  PaginationParams,
  ReadUseCase,
  SearchUseCase,
  SortCriteria,
  SortDirection,
  SortOrderUpdate,
  UpdateSortOrderUseCase,
  UpdateUseCase,
} from './common';

// Tag domain
export type {
  CreateTagInput,
  Tag,
  TagFilterCriteria,
  TagRepository,
  TagSortField,
  UpdateTagInput,
} from './tag';

// List domain
export type {
  CreateListInput,
  InterestListType,
  List,
  ListCategory,
  ListFilterCriteria,
  ListGroupCriteria,
  ListRepository,
  ListSortField,
  ListType,
  ListTypeConfig,
  NotesListType,
  ShoppingListType,
  UpdateListInput,
} from './list';

// Item domain
export type {
  BookMetadata,
  BookProviderRepository,
  BookSearchResult,
  CreateInterestItemInput,
  CreateItemInput,
  CreateNoteItemInput,
  CreateShoppingItemInput,
  ExternalMetadata,
  GameMetadata,
  GameProviderRepository,
  GameSearchResult,
  InterestItem,
  InterestItemFilterCriteria,
  InterestItemRepository,
  Item,
  ItemFilterCriteria,
  ItemGroupCriteria,
  ItemSortField,
  ItemType,
  MetadataCategory,
  MovieMetadata,
  MovieProviderRepository,
  MovieSearchResult,
  NoteItem,
  NoteItemFilterCriteria,
  NoteItemRepository,
  ShoppingItem,
  ShoppingItemFilterCriteria,
  ShoppingItemRepository,
  ShoppingListSummary,
  UpdateInterestItemInput,
  UpdateItemInput,
  UpdateNoteItemInput,
  UpdateShoppingItemInput,
} from './item';

// User domain
export type {
  CreateUserInput,
  CreateUserPreferencesInput,
  LayoutConfigs,
  SpecialLayoutKey,
  Theme,
  UpdateUserInput,
  UpdateUserPreferencesInput,
  User,
  UserPreferences,
  UserPreferencesRepository,
  UserRepository,
} from './user';
